<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class Expense extends Model
{
    use SoftDeletes;

    protected $fillable = ['expense_date', 'expense_category_id', 'amount', 'note','business_id','customer_id','vehicle_id','fuel','hour'];

    protected $dates = ['expense_date'];

    protected $casts=[
        'data'=>'array'
    ];

    public function expenseCategory()
    {
        return $this->belongsTo(ExpenseCategory::class)->withTrashed();
    }

    public function customer()
    {
        return $this->belongsTo(Customer::class)->withTrashed();
    }

    public function vehicle()
    {
        return $this->belongsTo(Vehicle::class);
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function($model){
            $model->business_id =  Auth::user()->business_id;
            $model->expense_id = get_option('expense_id_prefix').str_pad(Expense::withTrashed()->count()+1,get_option('invoice_length'),0,STR_PAD_LEFT);
        });
    }
}
