<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class PaymentToSupplier extends Model
{

    protected $fillable = ['payment_date','supplier_id','amount','note','customer_id'];

    protected $dates = ['payment_date'];



    public function supplier()
    {
        return $this->belongsTo(Supplier::class)->withTrashed();
    }

    public function site()
    {
        return $this->belongsTo(Customer::class,'customer_id','id')->withTrashed();
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function($model){
            $model->business_id =  Auth::user()->business_id;
        });
    }
}
