<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class PaymentFromCustomer extends Model
{
    protected $fillable = ['payment_date','amount','note'];

    protected $dates = ['payment_date'];



    public function customer()
    {
        return $this->belongsTo(Customer::class)->withTrashed();
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function($model){
            $model->business_id =  Auth::user()->business_id;
        });
    }
}
