<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class PurchaseProduct extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'purchase_price','quantity','total_price'
    ];

    public function product()
    {
        return $this->belongsTo(Product::class)
            ->with('unit')
            ->withTrashed();
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        // if (!Auth::user()->can('access_to_all_branch')) {
        //     static::addGlobalScope('branch', function (Builder $builder) {
        //         $builder->where('business_id', '=', Auth::user()->business_id);
        //     });
        // }
    }
}
